services:
  - type: web
    name: titounex-backend
    runtime: python
    rootDir: backend
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: CORS_ORIGIN
        value: https://titounex.vercel.app,http://localhost:3000
      - key: BACKEND_URL
        value: https://titounex-backend.onrender.com
      - key: NEXT_PUBLIC_BACKEND_URL
        value: https://titounex-backend.onrender.com
      - key: GOOGLE_CLIENT_ID
        sync: false
      - key: GOOGLE_CLIENT_SECRET
        sync: false
      - key: SECRET_KEY
        sync: false